-- Migration 057: Corrige link_maps de casas_retiro con los URLs reales.
-- El CSV original perdió los hipervínculos (solo guardó el texto visible); se
-- recuperaron del .xlsx (que sí conserva el hyperlink de cada celda).
-- Actualiza SOLO link_maps por codigo_interno; el resto no se toca.

BEGIN;

UPDATE public.casas_retiro c
SET link_maps = v.url, updated_at = now()
FROM (VALUES
  ('CASA-01', 'https://maps.app.goo.gl/VUYoy3Ww9Uev1Euz6'),
  ('CASA-02', 'https://maps.app.goo.gl/XLYLh9dEt7dUt1YF8'),
  ('CASA-03', 'https://maps.app.goo.gl/UZM1ifH6UGe1du55A'),
  ('CASA-04', 'https://maps.app.goo.gl/Wr9t3JyWhjGEA1z17'),
  ('CASA-05', 'https://maps.app.goo.gl/2rt7zquJUhh7V4Wa8'),
  ('CASA-06', 'https://maps.app.goo.gl/xiWdjVLzvviMfaYf7?g_st=aw'),
  ('CASA-07', 'https://maps.app.goo.gl/RKQypF3iidpgV6Jw9'),
  ('CASA-08', 'https://maps.app.goo.gl/U5hk7xsKktsy4Hie9'),
  ('CASA-09', 'https://maps.app.goo.gl/moZJBQipzBGWXapy7'),
  ('CASA-10', 'https://maps.app.goo.gl/3tu2zKi8ZtCahpxR7'),
  ('CASA-11', 'https://maps.app.goo.gl/BLNozjpv71roH5VN7'),
  ('CASA-12', 'https://maps.app.goo.gl/kGZc5y3u4KMkUq9Q7'),
  ('CASA-13', 'https://maps.app.goo.gl/5EdMqq1GMKKiEEUS9'),
  ('CASA-14', 'https://maps.app.goo.gl/i73bdeRwLPZJbCBP6'),
  ('CASA-15', 'https://maps.app.goo.gl/o9SscBpS1gpq7ViF9'),
  ('CASA-16', 'https://maps.app.goo.gl/cVG9v32e12Xuu1Hz6'),
  ('CASA-17', 'https://maps.app.goo.gl/iRubDk7SjfFkxJiFA'),
  ('CASA-18', 'https://maps.app.goo.gl/atY9Qzu3mrnvubht8'),
  ('CASA-19', 'https://maps.app.goo.gl/wkpr31Q6j9RJrukq6'),
  ('CASA-20', 'https://maps.app.goo.gl/Jkbpt8xt9WGRwvHY8'),
  ('CASA-21', 'https://maps.app.goo.gl/8u8XDynTJY2hhYYc9'),
  ('CASA-22', 'https://maps.app.goo.gl/DH3CoGSgGm74nEdWA'),
  ('CASA-24', 'https://maps.app.goo.gl/59nr9zaVyd3jUoFk9'),
  ('CASA-25', 'https://maps.app.goo.gl/83Cz83ZQD1bVXJ5NA'),
  ('CASA-26', 'https://maps.app.goo.gl/6po3WJYrZCp7exLLA'),
  ('CASA-27', 'https://maps.app.goo.gl/gGzt9i5sP3Dv3mMMA'),
  ('CASA-28', 'https://maps.app.goo.gl/AR9FWdde5Gw66MBMA'),
  ('CASA-29', 'https://maps.app.goo.gl/twWRnuZ3qGpTiRWg7'),
  ('CASA-30', 'https://maps.app.goo.gl/bYdasGwwHu5UnCYSA'),
  ('CASA-31', 'https://maps.app.goo.gl/hG8atEWopnRPC1zz7'),
  ('CASA-32', 'https://maps.app.goo.gl/RmSM7BzRWEmG72cQ6'),
  ('CASA-33', 'https://maps.app.goo.gl/bJ9YD9bfVqWfFr1W6'),
  ('CASA-34', 'https://maps.app.goo.gl/jbek3H7DWPfHgtei6'),
  ('CASA-35', 'https://maps.app.goo.gl/cQTHYtktJxjPH4hn8'),
  ('CASA-36', 'https://maps.app.goo.gl/WVpLCGTrh2kmNnWy9'),
  ('CASA-37', 'https://maps.app.goo.gl/mxVs9ZyP88VcsgBz8'),
  ('CASA-38', 'https://maps.app.goo.gl/6TmZgJqdwEU8oi4y7'),
  ('CASA-39', 'https://maps.app.goo.gl/7urdAWSzcDzLGmsE8'),
  ('CASA-41', 'https://maps.app.goo.gl/9yNAJCzpinQd4HkM8'),
  ('CASA-42', 'https://maps.app.goo.gl/zfmyTgk4W5k7MynJA'),
  ('CASA-43', 'https://maps.app.goo.gl/iJcM26Gs2MbWHGrT6'),
  ('CASA-44', 'https://maps.app.goo.gl/QzQDP6a2PGq9dm7d6'),
  ('CASA-45', 'https://maps.app.goo.gl/793g5Wk1QPjaDPLo9'),
  ('CASA-46', 'https://maps.app.goo.gl/hgvKF35rpofHKnPWA'),
  ('CASA-47', 'https://maps.app.goo.gl/nQym1iHGfnxXVkVg7'),
  ('CASA-48', 'https://maps.app.goo.gl/KcD9ndTEiuh4yR5RA'),
  ('CASA-49', 'https://maps.app.goo.gl/qntJ4WHqGBS6MmoC6'),
  ('CASA-50', 'https://maps.app.goo.gl/PWiNeb8hs2waqJVQ9'),
  ('CASA-51', 'https://maps.app.goo.gl/gENJUtdoRrBuarkP8'),
  ('CASA-52', 'https://maps.app.goo.gl/uWd9AKw54ThRCbGs8'),
  ('CASA-53', 'https://maps.app.goo.gl/nYrgQdCPYn6Vc8Gz6'),
  ('CASA-54', 'https://maps.app.goo.gl/L187VWWoJeDQTfP1A'),
  ('CASA-55', 'https://maps.app.goo.gl/oqZVocykaJP6iMnw5'),
  ('CASA-56', 'https://maps.app.goo.gl/obARGgKjRiA8HeoQ9'),
  ('CASA-57', 'https://maps.app.goo.gl/ioQ7D4xSikLjZ83j7'),
  ('CASA-58', 'https://maps.app.goo.gl/cWmQEDzv6fA38vvx6'),
  ('CASA-59', 'https://maps.app.goo.gl/q86F3p94wNTqFQx99'),
  ('CASA-60', 'https://maps.app.goo.gl/PmV8yYhixCaopDSL6'),
  ('CASA-61', 'https://maps.app.goo.gl/mA672nhZmDFd5Qy87'),
  ('CASA-62', 'https://maps.app.goo.gl/B4FrJfZFQoYzmZbDA'),
  ('CASA-63', 'https://maps.app.goo.gl/ZpbeJjXWXaVqvFkw6'),
  ('CASA-64', 'https://maps.app.goo.gl/EKjVeTe3RzVAw1oj9'),
  ('CASA-65', 'https://maps.app.goo.gl/gbYHBrbbqjJAc38N7'),
  ('CASA-66', 'https://maps.app.goo.gl/y79dHkiAvHZAzzuC7'),
  ('CASA-67', 'https://maps.app.goo.gl/77No9rAwoqNzo7g2A'),
  ('CASA-68', 'https://maps.app.goo.gl/62cSJQC99f1q3rnb6'),
  ('CASA-69', 'https://maps.app.goo.gl/jb4xnTHQ7K85dWi86'),
  ('CASA-70', 'https://maps.app.goo.gl/NDsaVLHZTZo7NQB37'),
  ('CASA-71', 'https://maps.app.goo.gl/oZdCRZkVo1xmn3fZ7'),
  ('CASA-72', 'https://maps.app.goo.gl/FYHNzyBGyE8RTGk6A'),
  ('CASA-73', 'https://maps.app.goo.gl/JHwYueBwBn12Bmn87'),
  ('CASA-74', 'https://maps.app.goo.gl/aTbfcZKBxdpUNH8w6'),
  ('CASA-75', 'https://maps.app.goo.gl/ifD6UCFksS13TtpL8'),
  ('CASA-76', 'https://maps.app.goo.gl/wm9TKx8oRc9ZgYcF7'),
  ('CASA-77', 'https://maps.app.goo.gl/w4kAjyaRwXtYdT5v5'),
  ('CASA-78', 'https://maps.app.goo.gl/mLnJa5u2QWWXikDU7'),
  ('CASA-79', 'https://maps.app.goo.gl/J5L6Ydwm6MiniqdQA'),
  ('CASA-80', 'https://maps.app.goo.gl/WDeknSGzgtZ6q3AdA'),
  ('CASA-81', 'https://maps.app.goo.gl/EUAXJgTQ9GPA4Mhc8'),
  ('CASA-83', 'https://maps.app.goo.gl/5DLa745ukN7H4yKb7'),
  ('CASA-84', 'https://maps.app.goo.gl/tjhrWsfoUUu2gYY38'),
  ('CASA-85', 'https://maps.app.goo.gl/8FMFZ9PbbosEmBAV9'),
  ('CASA-86', 'https://maps.app.goo.gl/bkFkkDPMjozDrCX39'),
  ('CASA-87', 'https://maps.app.goo.gl/xN787X5DWXDjqqEk7'),
  ('CASA-88', 'https://maps.app.goo.gl/ow1AN49pBoJracFt6'),
  ('CASA-89', 'https://maps.app.goo.gl/pd4ips7Fx8aAfdS38'),
  ('CASA-90', 'https://maps.app.goo.gl/ZeHmVbLPJgoBmHUP7'),
  ('CASA-91', 'https://goo.gl/maps/1qnibWM7WkQMQ4zG9'),
  ('CASA-92', 'https://www.google.com/maps/place/Parroquia+San+Antonio,+Gral.+Jos%C3%A9+de+San+Mart%C3%ADn,+Chaco/@-26.537152,-59.3417235,15z/data=!4m13!1m7!3m6!1s0x0:0x7f39876bbc6263bc!2sParroquia+San+Antonio,+Gral.+Jos%C3%A9+de+San+Mart%C3%ADn,+Chaco!3b1!8m2!3d-26.537152!4d-59.3417235!3m4!1s0x944389c9c44fd3e5:0x7f39876bbc6263bc!8m2!3d-26.537152!4d-59.3417235'),
  ('CASA-93', 'https://goo.gl/maps/GK5qxnJwELgXXByx7')
) AS v(codigo, url)
WHERE c.codigo_interno = v.codigo;

COMMIT;

-- Verificación: casas con link_maps que NO es URL (deberían quedar solo las 3 sin link):
-- SELECT codigo_interno, nombre, link_maps FROM public.casas_retiro
--   WHERE link_maps IS NOT NULL AND link_maps NOT LIKE 'http%';
